version: '3.8'

services:
  api:
    container_name: "printscript-service-api"
    build:
      context: ../printscript-service
      dockerfile: Dockerfile.multi
    ports:
      - "8004:8080"
    environment: # Poner estas variables en un archivo .env
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: compose-db
      DB_HOST: postgres_db
      DB_PORT: 5434
  db:
    container_name: printscript-service-db
    image: postgres:latest
    ports:
      - "5434:5432"
    environment: # Poner estas variables en un archivo .env
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: snippet-manager-db
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "tomi.serra@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  pgdata:
    external: false