services:
  db:
    container_name: printscript-service-db
    image: postgres:latest
    ports:
      - "5434:5432"
    environment: # Poner estas variables en un archivo .env
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: printscript-service-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: false
