version: '3.8'

services:
  api:
    container_name: "printscript-service-api"
    build:
      context: ../printscript-service
      dockerfile: Dockerfile
    ports:
      - "8004:8080"
    environment: # Poner estas variables en un archivo .env
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: db
      DB_HOST: snippet-manager-db
      DB_PORT: 5434
    env_file:
      - .env
  db:
    container_name: printscript-service-db
    image: postgres:latest
    ports:
      - "5434:5432"
    environment: # Poner estas variables en un archivo .env
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: snippet-manager-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: false