spring:
  application:
    name: back
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:printscript-service-db}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:admin}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:admin}}
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI}

permission:
  manager:
    url: ${PERMISSION_MANAGER_URL:http://localhost:8003}

snippet:
  manager:
    url: ${SNIPPET_MANAGER_URL:http://localhost:8000}

asset:
  manager:
    url: ${ASSET_MANAGER_URL:http://localhost:8080}

auth0:
  audience: ${AUTH0_AUDIENCE}

server:
  port: ${DOCKER_PORT:8004}