spring:
  application:
    name: back
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI}
  jpa:
    open-in-view: false
    autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
        - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

permission:
  manager:
    url: ${PERMISSION_MANAGER_URL:http://localhost:8003}

snippet:
  manager:
    url: ${SNIPPET_MANAGER_URL:http://localhost:8000}

asset:
  manager:
    url: ${ASSET_MANAGER_URL:http://localhost:8082}

auth0:
  audience: ${AUTH0_AUDIENCE}

server:
  port: ${DOCKER_PORT:8004}

redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

stream:
  key:
    lint: "lint-queue"
  group:
    lint: "lint-group"
