name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Paso 2: Configurar JDK
      - name: Config JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Paso 3: Configurar Gradle Cache
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Paso 4: Configurar credenciales para GitHub Packages
      - name: Set up GitHub Packages credentials
        run: |
          echo "gpr.user=${{ secrets.GPR_USER }}" >> $GITHUB_ENV
          echo "gpr.token=${{ secrets.DOCKER_TOKEN }}" >> $GITHUB_ENV

      # Paso 5: Construir el proyecto con Gradle
      - name: Build Gradle
        env:
          USERNAME : ${{ secrets.GPR_USER }}
          TOKEN : ${{ secrets.DOCKER_TOKEN }}
        run: gradle assemble --no-daemon

      # Paso 6: Iniciar sesión en GitHub Container Registry
      - name: Login GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 7: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build --build-arg GPR_USER=${{ secrets.GPR_USER }} --build-arg GPR_TOKEN=${{ secrets.DOCKER_TOKEN }} -t ghcr.io/${{ github.repository }}:latest .

      # Paso 8: Push de la imagen Docker a GHCR
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest